const initialTimeSlot = [
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
  ["open", -1],
];

export default [...initialTimeSlot];
